INSERT INTO JUNCTION (JID,TITLE,CMD,CREATED_AT) VALUES (03,'JUN03','resume',CURRENT_TIMESTAMP);   
INSERT INTO LIGHTS (JID,DIRECTION, CODE,COLOR, CSTATUS, DURATION, CREATED_AT) VALUES (3, 'NORTH', 'NS','GREEN','NS-GREEN',30,CURRENT_TIMESTAMP);
INSERT INTO LIGHTS (JID,DIRECTION, CODE,COLOR, CSTATUS, DURATION, CREATED_AT) VALUES (3, 'SOUTH', 'NS','GREEN','NS-GREEN',30,CURRENT_TIMESTAMP);    
INSERT INTO LIGHTS (JID,DIRECTION, CODE,COLOR, CSTATUS, DURATION, CREATED_AT) VALUES (3, 'EAST', 'EW','RED','EW-RED',30,CURRENT_TIMESTAMP);    
INSERT INTO LIGHTS (JID,DIRECTION, CODE,COLOR, CSTATUS, DURATION, CREATED_AT) VALUES (3, 'WEST', 'EW','RED','EW-RED',30,CURRENT_TIMESTAMP);  
commit;
